Fix Twitter Link (README.md)
pydatadelhi/old_website_2 pull request #2
Opened 2019-05-23 05:37 UTC by code-monk08

2019-05-23 12:46 UTC, code-monk08 commented
Work In Progress: Common Footer

It currently looks like this:
![image](https://user-images.githubusercontent.com/19390263/58253802-de4a1f00-7d86-11e9-9fb1-95f669824c12.png)

Work needed to be done: 

- [ ] to correct font awesome icons & add suitable links.

- [ ] to change *About PyData* text.

2019-05-23 13:04 UTC, code-monk08 commented
@Arsh23 does it look alright?

2019-05-23 13:11 UTC, ramantehlan requested changes
I think the progress so far is good, can you also upload the responsive view of the changes.

2019-05-23 13:11 UTC, ramantehlan commented on src/App.vue
> +</style>
Add a new line here. :)

2019-05-23 13:11 UTC, ramantehlan commented on package.json
> +    "@fortawesome/vue-fontawesome": "^0.1.6",
Where are you using these packages?

2019-05-23 13:54 UTC, code-monk08 commented on src/App.vue
> +</style>
Sure, will do that.

2019-05-23 13:56 UTC, code-monk08 commented on package.json
> +    "@fortawesome/vue-fontawesome": "^0.1.6",
Adding font awesome icon support in Vue, will remove unnecessary packages after I am done with the above mentioned work.

2019-05-23 16:11 UTC, ramantehlan commented on package.json
> +    "@fortawesome/vue-fontawesome": "^0.1.6",
Check index.html, I guess the support is already added there.

2019-05-26 15:13 UTC, code-monk08 commented
![image](https://user-images.githubusercontent.com/19390263/58383641-e90aeb00-7ff6-11e9-825a-529a9af46ae2.png)

@ramantehlan  @codekhal @Arsh23 Please take a look !

2019-05-26 15:14 UTC, code-monk08 commented
It's fully responsive too!

2019-05-26 15:21 UTC, code-monk08 commented on package.json
> +    "@fortawesome/vue-fontawesome": "^0.1.6",
Yes, Thanks.

2019-05-26 15:29 UTC, code-monk08 commented
> I think the progress so far is good, can you also upload the responsive view of the changes.

one more: 
![image](https://user-images.githubusercontent.com/19390263/58383866-22dcf100-7ff9-11e9-98f5-65814fdc42cc.png)

2019-05-27 06:42 UTC, code-monk08 commented
Update: 
![image](https://user-images.githubusercontent.com/19390263/58400438-9d008a80-8078-11e9-8bea-b563e80224de.png)

2019-05-27 09:19 UTC, code-monk08 commented
Sponsors Page Update:
![image](https://user-images.githubusercontent.com/19390263/58409870-a5fc5680-808e-11e9-8bcc-aae014247ddf.png)

2019-05-27 09:42 UTC, code-monk08 commented
Update Archive Page: 
![image](https://user-images.githubusercontent.com/19390263/58411384-d0034800-8091-11e9-9475-4191f73890f4.png)

2019-05-27 11:00 UTC, merged